src/config/routes.rb
Rails.application.routes.draw do
  resources :forum_threads do
    resources :forum_posts
  end

  root to: "forum_threads#index"
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
  belongs_to :forum_thread
  validates :body, presence: true
end

src/app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
  has_many :forum_posts
end

src/app/models/table.rb
class Table
  attr_accessor :name, :player_estimates

  @tables = Hash.new do |hash, name|
    hash[name] = Table.new(name)
  end

  def self.find_or_create(name)
    @tables[name]
  end

  def initialize(name, player_estimates = {})
    @name = name
    @player_estimates = player_estimates
  end

  def players
    @player_estimates.keys
  end

  def enter(player)
    estimate(player)
  end

  def leave(player)
    @player_estimates.delete(player)
  end

  def estimate(player, estimation = nil)
    @player_estimates[player] = estimation
  end

  def estimates
    player_estimates.values.map(&:to_f).reject { |es| es.nil? || es <= 0 }
  end

  def viable_estimations
    return estimates.sort[1..-2] if estimates.count > 3
    estimates
  end

  def average
    return 0 unless viable_estimations.any?
    viable_estimations.inject(0, :+) / viable_estimations.count
  end

  def reset!
    players.each do |player|
      @player_estimates[player] = nil
    end
  end

  def to_h
    {
      name: name,
      player_estimates: player_estimates,
      player_count: player_estimates.count,
      average: average
    }
  end

  def to_s
    "table_#{name}"
  end
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

src/app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new(forum_post_params)
    if @forum_post.save
      flash[:notice] = "New post submitted"
      # render partial: 'comments', collection: @forum_thread.forum_posts, as: :forum_post, change: [:comments]    redirect_to @forum_thread, change: [:comments]
      redirect_to @forum_thread, change: [:comments]
    else
      render partial: "form", change: :new_forum_post
    end
  end

  def update
    @forum_post = @forum_thread.forum_posts.find(params[:id])
    @forum_post.update(forum_post_params)
    flash[:notice] = "New post updated"
    redirect_to @forum_thread, change: [:comments]
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

src/app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :set_forum_thread, only: [:show, :edit, :update, :destroy]

  # GET /forum_threads
  # GET /forum_threads.json
  def index
    @forum_threads = ForumThread.all
  end

  # GET /forum_threads/1
  # GET /forum_threads/1.json
  def show
    @forum_post = ForumPost.new
  end

  # GET /forum_threads/new
  def new
    @forum_thread = ForumThread.new
  end

  # GET /forum_threads/1/edit
  def edit
  end

  # POST /forum_threads
  # POST /forum_threads.json
  def create
    @forum_thread = ForumThread.new(forum_thread_params)

    respond_to do |format|
      if @forum_thread.save
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully created.' }
        format.json { render :show, status: :created, location: @forum_thread }
      else
        format.html { render :new }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_threads/1
  # PATCH/PUT /forum_threads/1.json
  def update
    respond_to do |format|
      if @forum_thread.update(forum_thread_params)
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_thread }
      else
        format.html { render :edit }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_threads/1
  # DELETE /forum_threads/1.json
  def destroy
    @forum_thread.destroy
    respond_to do |format|
      format.html { redirect_to forum_threads_url, notice: 'Forum thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_thread_params
      params.require(:forum_thread).permit(:name)
    end
end

src/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table

  # This is the only action actually needed, because everything is handled through actioncable
  def show
  end

  def estimate
    fail 'Why do you fail me, ActionCable!?!'
    # @table.estimate(params[:player], params[:estimate])
    # redirect_to table_path(@table.name)
  end

  private

  def set_table
    @table = Table.find_or_create(params[:id])
  end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

src/app/views/forum_posts/_form.html.erb
<%= form_for [@forum_thread, @forum_post], remote: true do |f| %>
  <% if @forum_post.errors.any? %>
    <div>ERRORS</div>
  <% end %>

  <div><%= f.text_area :body %></div>
  <%= f.submit %>
<% end %>

src/app/views/forum_threads/_comments.html.erb
<div id="comments:<%= forum_post.id %>">
  <%= simple_format forum_post.body %>
</div>

src/app/views/forum_threads/_form.html.erb
<%= form_for(@forum_thread) do |f| %>
  <% if @forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% @forum_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/forum_threads/edit.html.erb
<h1>Editing Forum Thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_thread %> |
<%= link_to 'Back', forum_threads_path %>

src/app/views/forum_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Threads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_threads.each do |forum_thread| %>
      <tr>
        <td><%= forum_thread.name %></td>
        <td><%= link_to 'Show', forum_thread %></td>
        <td><%= link_to 'Edit', edit_forum_thread_path(forum_thread) %></td>
        <td><%= link_to 'Destroy', forum_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum thread', new_forum_thread_path %>

src/app/views/forum_threads/new.html.erb
<h1>New Forum Thread</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_threads_path %>

src/app/views/forum_threads/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @forum_thread.name %></h1>

<span><%= pluralize @forum_thread.forum_posts.count, "Post" %></span>
<%= link_to 'Edit', edit_forum_thread_path(@forum_thread) %>

<div id="comments">
    <%= render partial: 'comments', collection: @forum_thread.forum_posts, as: :forum_post %>
</div>

<hr />
<%= render partial: "forum_posts/form" %>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

src/app/views/tables/show.html.erb
<h1><%= "Table #{@table.name}" %></h1>

<dl id="estimates">
  <% @table.player_estimates.each do |player, estimation| %>
      <dt><%= player %></dt>
      <dd><%= estimation %></dd>
  <% end %>
</dl>
<hr>
<p>
  Average: <span id="average"><%= @table.average %></span>
</p>
<hr>
<p>
  Add an estimate: <br />
  <%= form_tag(table_path(@table.name), method: :post) do %>
      <%= text_field_tag(:player) %>
      <%= number_field_tag(:estimate) %>
      <%= submit_tag("Estimate!") %>
      <%= button_tag "Reset!", type: :reset %>
  <% end %>
</p>